### ISSUE TITLE
i ll be happy if there a setting for Duplication in VSC for the Anki Extension 

### ISSUE THREAD

**Issue by abedahmeduhp** [jasonwilliams/anki#20] opened 2020-09-29 22:10 UTC
firstly, thank you for the huge effort to make this great extension ..
i'll be so happy if you can't add in settings of VSC for the addon the ability to allow duplicate cards ..
it's helpful for me...
for example if i wrote the following cards 
![image](https://user-images.githubusercontent.com/62298107/94621973-306b5080-02a9-11eb-8272-fe0873921e2c.png)
then coming back the next day and forgetting about the Front Insight Card exists before .. and i wrote some content like : 
![image](https://user-images.githubusercontent.com/62298107/94622052-5bee3b00-02a9-11eb-8745-7be32174258d.png)
The card won't be available inside Anki ... can you add this feature for me please ? thank you

**Comment by jasonwilliams** [comment] 2020-09-29 22:30
is this a request to overwrite the previous card if you're add new content?

**Comment by abedahmeduhp** [comment] 2020-09-29 22:35
no, i don't want to overwrite the previous card ...
i want to see in the Anki Browser 
--------------------
Front : Insight 
Back : hmmmm
---------------------
Front : Insight 
Back : useful information for a topic ...

i use anki for taking notes that's why sometimes, i can't notice there is Front Insight exists before .. but with different content 

Thanks again

**Comment by jasonwilliams** [comment] 2020-09-29 23:55
Ok, this sounds like a duplicate of https://github.com/jasonwilliams/anki/issues/16 I will most likely add a duplicate option I’m a future release

**Closed** 2020-10-07 08:33 UTC
